### ISSUE TITLE
What is the code for the search bar that's circled in blue in screenshot 1

### ISSUE THREAD

**Issue by luke827** [rbrundritt/SimpleUwpAzureMaps#1]
What is the code for the search bar that's circled in blue in screenshot 1
![Screenshot (1)](https://github.com/user-attachments/assets/c347eb29-d8e8-4936-85d8-31ef1d028499)

**Comment by rbrundritt** [comment]
See this file https://github.com/rbrundritt/SimpleUwpAzureMaps/blob/main/SimpleUWPMapApp/SimpleUWPMapApp/Assets/html/MapApp.html

You want the search function in javascript and the search Control div in the html.
