### ISSUE TITLE
I've put in my subscriptions key thats works fine but when I search for Sydney and Brisbane it works but it wont pickup location for Beijing?

### ISSUE THREAD

**Issue by luke827** [rbrundritt/SimpleUwpAzureMaps#3]
I've put in my authentication subscription keys to mapapp.html that works fine when I search for Sydney and Brisbane it works fine but when I search for Beijing it won't go to its location on map?

**Comment by rbrundritt** [comment]
I just tried and it worked fine. This is just a simple example of getting Azure Maps working in a UWP app, and doesn't dive deep into the Azure Maps platform.

**Comment by luke827** [comment]
It does not zoom in load going into its exact location position that's Beijing everything else works fine when I search for Beijing it only goes to its fully zoomed out position of the whole map that's it as shown in screenshot
![Screenshot (625)](https://github.com/user-attachments/assets/2157e7a3-d6ee-45ff-911f-f08645740d5f)

**Comment by luke827** [comment]
In the screenshots that's all where it goes?

**Comment by rbrundritt** [comment]
You don't get it. Go use something else. I've wasted well over a hundred hours of my life on you. I'm done.
